# http://docs.travis-ci.com/user/languages/c/
# start from https://github.com/rubinius/rubinius/blob/master/.travis.yml
language: c
sudo: false

compiler:
  - clang
  - gcc
os:
  - linux
# - osx
env:
  - DCNN=1
  - DCNN=0

matrix:
  exclude:
    - os: osx
      env: DCNN=1
    - os: osx
      compiler: gcc
#   allow_failures:
#     - compiler: clang

# get caffe from ppa
before_install:
  - if [ "$TRAVIS_OS_NAME" = linux ] && [ "$DCNN" = 1 ]; then sudo add-apt-repository ppa:lemonsqueeze/pachi -y ; fi
  - if [ "$TRAVIS_OS_NAME" = linux ] && [ "$DCNN" = 1 ]; then sudo apt-get update -q ; fi
  - if [ "$TRAVIS_OS_NAME" = linux ] && [ "$DCNN" = 1 ]; then sudo apt-get install libcaffe-cpu-dev -y ; fi

# https://blog.lukaspradel.com/continuous-integration-for-cmake-projects-using-travis-ci/  
script:
  - make -j2 DCNN=$DCNN
  - make test
